# Generated by Django 3.1.4 on 2020-12-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homecontent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_img', models.ImageField(upload_to='pics')),
                ('offers', models.CharField(max_length=15)),
                ('pd_title', models.CharField(max_length=10)),
                ('pd_name', models.TextField()),
                ('pd_disc', models.TextField()),
                ('pd_img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
