# Generated by Django 3.1.4 on 2020-12-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenoptical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecontent',
            name='pd_title',
            field=models.CharField(max_length=20),
        ),
    ]
