# Generated by Django 3.1.4 on 2020-12-31 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenoptical', '0002_auto_20201230_0501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homecontent',
            old_name='bg_img',
            new_name='bg_img_1026x660',
        ),
        migrations.RenameField(
            model_name='homecontent',
            old_name='pd_img',
            new_name='pd_img_330x260',
        ),
    ]
